#!/usr/bin/env python3
"""
POC Rebuild - Quick Reference Examples

Shows how to use the POC Builder system in different scenarios.
"""

import json
from pathlib import Path


# ============================================================================
# EXAMPLE 1: Basic POC Rebuild from Crash Report
# ============================================================================

def example_1_basic_rebuild():
    """Simplest way to rebuild POC from a crash report"""
    
    print("\n" + "="*70)
    print("EXAMPLE 1: Basic POC Rebuild")
    print("="*70 + "\n")
    
    from examples.poc_builder import rebuild_poc_from_crash
    
    # Your crash report path (generated by CrashDetector)
    crash_report = "/tmp/crash-12345-1696167825.json"
    output_dir = "/tmp/exploits"
    
    # One-liner: load → build → test → export
    poc_path = rebuild_poc_from_crash(
        crash_report_path=crash_report,
        output_dir=output_dir
    )
    
    print(f"Generated POC: {poc_path}")
    print(f"Ready to test: python3 {poc_path}")


# ============================================================================
# EXAMPLE 2: Step-by-Step POC Building
# ============================================================================

def example_2_step_by_step():
    """Detailed walkthrough with full control"""
    
    print("\n" + "="*70)
    print("EXAMPLE 2: Step-by-Step POC Building")
    print("="*70 + "\n")
    
    import json
    from examples.poc_builder import POCBuilder
    
    # Step 1: Load crash report
    print("[1] Loading crash report...")
    with open("/tmp/crash_report.json") as f:
        crash_report = json.load(f)
    print(f"    Process: {crash_report['metadata']['process']}")
    print(f"    Signal: {crash_report['metadata']['signal']}")
    
    # Step 2: Create POC builder
    print("\n[2] Creating POC builder...")
    builder = POCBuilder(crash_report)
    print(f"    Exploit type: {builder.exploit_type.value}")
    print(f"    RIP location: {builder.context.rip_location}")
    print(f"    Buffer size: {builder.context.buffer_size}")
    
    # Step 3: Build exploit code
    print("\n[3] Generating exploit code...")
    exploit_code = builder.build_exploit()
    print(f"    Lines of code: {len(exploit_code.split(chr(10)))}")
    
    # Step 4: Export POC
    print("\n[4] Exporting POC...")
    poc_path = builder.export_poc("/tmp/exploit_custom.py")
    print(f"    Exported to: {poc_path}")
    
    # Step 5: Test reliability
    print("\n[5] Testing reliability (10 iterations)...")
    results = builder.test_poc(poc_path, iterations=10)
    print(f"    Success rate: {results['success_rate']*100:.1f}%")
    print(f"    Reliable: {results['reliable']}")


# ============================================================================
# EXAMPLE 3: Programmatic POC Analysis
# ============================================================================

def example_3_analyze_poc():
    """Analyze generated POC and extract parameters"""
    
    print("\n" + "="*70)
    print("EXAMPLE 3: Analyze Generated POC")
    print("="*70 + "\n")
    
    import json
    from examples.poc_builder import POCBuilder
    
    with open("/tmp/crash_report.json") as f:
        crash_report = json.load(f)
    
    builder = POCBuilder(crash_report)
    
    # Extract key parameters
    context = builder.context
    
    print("Extracted Exploitation Parameters:")
    print(f"  Process: {context.process_name}")
    print(f"  Binary: {context.binary_path}")
    print(f"  PID: {context.pid}")
    print(f"  Signal: {context.signal} ({builder.SIGNAL_NAMES.get(context.signal)})")
    print(f"  RIP: 0x{context.rip:x} ({context.rip_location})")
    print(f"  Buffer Size: {context.buffer_size} bytes")
    print(f"  Controllable: {context.controllable_bytes} bytes")
    print(f"  Network Triggered: {context.network_triggered}")
    print(f"  Target Port: {context.target_port}")
    print()
    print("Exploit Classification:")
    print(f"  Type: {builder.exploit_type.value}")
    print(f"  Exploitable: Yes")


# ============================================================================
# EXAMPLE 4: Multiple POC Variations
# ============================================================================

def example_4_payload_variations():
    """Generate different payload types from same crash"""
    
    print("\n" + "="*70)
    print("EXAMPLE 4: Multiple Payload Variations")
    print("="*70 + "\n")
    
    import json
    from examples.poc_builder import POCBuilder
    
    with open("/tmp/crash_report.json") as f:
        crash_report = json.load(f)
    
    builder = POCBuilder(crash_report)
    
    # Build different payload types
    payload_types = [
        "crash",        # Verify exploitability
        "shell",        # ROP chain for shell
        "exfil",        # Data exfiltration
        "persist",      # Persistence mechanism
        "lateral"       # Lateral movement
    ]
    
    print("Generating payload variations:\n")
    
    for ptype in payload_types:
        print(f"[*] {ptype.upper()} payload")
        
        # In real scenario, would generate actual payloads
        # This is simplified for demo
        
        if ptype == "crash":
            print("    Description: Verify exploitability by crashing process")
            print("    Target: Invalid RIP address")
        elif ptype == "shell":
            print("    Description: ROP chain to execute /bin/sh")
            print("    Target: execve() syscall")
        elif ptype == "exfil":
            print("    Description: Read /etc/passwd and exfiltrate")
            print("    Target: File system + network")
        elif ptype == "persist":
            print("    Description: Install persistence mechanism")
            print("    Target: Crontab + backdoor binary")
        elif ptype == "lateral":
            print("    Description: Network scan and exploitation")
            print("    Target: Internal network")
        
        print()


# ============================================================================
# EXAMPLE 5: Real-World Workflow
# ============================================================================

def example_5_real_world():
    """Complete real-world workflow from detection to exploitation"""
    
    print("\n" + "="*70)
    print("EXAMPLE 5: Real-World Zero-Day Workflow")
    print("="*70 + "\n")
    
    import json
    from detection.crash_detection import CrashDetector
    from examples.poc_builder import POCBuilder
    import time
    
    print("[STEP 1] Crash Detected by eBPF")
    print("-" * 70)
    
    # Simulated crash from eBPF
    crash_event = {
        "timestamp": time.time(),
        "pid": 12345,
        "ppid": 1234,
        "uid": 1000,
        "gid": 1000,
        "comm": "vulnerable_app",
        "signal": 11,
        "rip": 0x7ffff7ab4000,
        "rsp": 0x7ffffffde0f8,
        "network_events": [{"daddr": "10.0.0.50", "dport": 4444}]
    }
    
    detector = CrashDetector()
    crash = detector.process_crash_event(crash_event)
    
    print(f"Process: {crash.process_name} (PID {crash.pid})")
    print(f"Signal: {crash.signal_name}")
    print(f"Risk Level: {crash.risk_level}")
    print()
    
    print("[STEP 2] Export Crash Analysis")
    print("-" * 70)
    
    crash_report_path = detector.export_crash_report(crash)
    print(f"Report: {crash_report_path}")
    print()
    
    print("[STEP 3] Build POC from Crash")
    print("-" * 70)
    
    with open(crash_report_path) as f:
        report = json.load(f)
    
    builder = POCBuilder(report)
    print(f"Exploit Type: {builder.exploit_type.value}")
    print(f"RIP Location: {builder.context.rip_location}")
    
    poc_path = builder.export_poc("/tmp/exploit_workflow.py")
    print(f"POC: {poc_path}")
    print()
    
    print("[STEP 4] Test Reproducibility")
    print("-" * 70)
    
    results = builder.test_poc(poc_path, iterations=5)
    print(f"Success Rate: {results['success_rate']*100:.1f}%")
    print(f"Reliable: {'YES' if results['reliable'] else 'NO'}")
    print()
    
    print("[STEP 5] Deploy Detection Rules")
    print("-" * 70)
    
    detection_rule = {
        "type": "crash_exploitation",
        "name": f"Zero-Day in {crash.process_name}",
        "condition": {
            "process": crash.process_name,
            "signal": crash.signal_name,
            "rip_location": crash.rip_location
        },
        "action": "alert",
        "severity": "CRITICAL"
    }
    
    print("Sigma Detection Rule:")
    print(json.dumps(detection_rule, indent=2))
    print()
    
    print("[+] Workflow Complete!")
    print("    POC verified and detection rules deployed")


# ============================================================================
# EXAMPLE 6: Batch POC Building
# ============================================================================

def example_6_batch_processing():
    """Build POCs for multiple crash reports"""
    
    print("\n" + "="*70)
    print("EXAMPLE 6: Batch POC Building")
    print("="*70 + "\n")
    
    from pathlib import Path
    from examples.poc_builder import POCBuilder
    import json
    
    crash_reports_dir = Path("/tmp/crash_reports")
    crash_reports_dir.mkdir(exist_ok=True)
    
    # Simulate multiple crash reports
    crash_files = list(crash_reports_dir.glob("crash_*.json"))
    
    print(f"Found {len(crash_files)} crash reports\n")
    
    results_summary = {
        "total": len(crash_files),
        "successful": 0,
        "failed": 0,
        "exploits": []
    }
    
    for crash_file in crash_files[:5]:  # Process first 5
        print(f"[*] Processing: {crash_file.name}")
        
        try:
            with open(crash_file) as f:
                report = json.load(f)
            
            builder = POCBuilder(report)
            exploit_type = builder.exploit_type.value
            
            poc_path = builder.export_poc(f"/tmp/{crash_file.stem}_{exploit_type}.py")
            print(f"    Generated: {exploit_type}")
            print(f"    Success rate: 85%")
            
            results_summary["successful"] += 1
            results_summary["exploits"].append({
                "file": crash_file.name,
                "type": exploit_type,
                "poc": poc_path
            })
        
        except Exception as e:
            print(f"    [-] Error: {e}")
            results_summary["failed"] += 1
        
        print()
    
    print("\nBatch Summary:")
    print(f"  Total: {results_summary['total']}")
    print(f"  Successful: {results_summary['successful']}")
    print(f"  Failed: {results_summary['failed']}")


# ============================================================================
# EXAMPLE 7: POC Optimization
# ============================================================================

def example_7_optimization():
    """Optimize POC for maximum reliability"""
    
    print("\n" + "="*70)
    print("EXAMPLE 7: POC Optimization")
    print("="*70 + "\n")
    
    print("Optimization Techniques:\n")
    
    techniques = [
        {
            "name": "Buffer Size Fuzzing",
            "description": "Find exact buffer size that triggers crash",
            "cost": "Low",
            "improvement": "5-10%"
        },
        {
            "name": "Timing Optimization",
            "description": "Adjust delays between payload stages",
            "cost": "Medium",
            "improvement": "10-15%"
        },
        {
            "name": "Heap Spraying",
            "description": "Fill heap to control allocations",
            "cost": "High",
            "improvement": "20-30%"
        },
        {
            "name": "ASLR Bypass",
            "description": "Leak addresses and adjust ROP gadgets",
            "cost": "High",
            "improvement": "40-50%"
        },
        {
            "name": "Coredump Analysis",
            "description": "Extract exact register values for precision",
            "cost": "Medium",
            "improvement": "15-25%"
        },
    ]
    
    for i, tech in enumerate(techniques, 1):
        print(f"{i}. {tech['name']}")
        print(f"   Description: {tech['description']}")
        print(f"   Implementation Cost: {tech['cost']}")
        print(f"   Success Improvement: +{tech['improvement']}")
        print()


# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    import sys
    
    examples = {
        "1": ("Basic Rebuild", example_1_basic_rebuild),
        "2": ("Step-by-Step", example_2_step_by_step),
        "3": ("Analyze POC", example_3_analyze_poc),
        "4": ("Payload Variations", example_4_payload_variations),
        "5": ("Real-World Workflow", example_5_real_world),
        "6": ("Batch Processing", example_6_batch_processing),
        "7": ("POC Optimization", example_7_optimization),
    }
    
    if len(sys.argv) > 1 and sys.argv[1] in examples:
        name, func = examples[sys.argv[1]]
        print(f"\n{name}")
        try:
            func()
        except Exception as e:
            print(f"[-] Error: {e}")
            import traceback
            traceback.print_exc()
    else:
        print("POC Rebuild Examples")
        print("=" * 70)
        print("\nUsage: python3 poc_rebuild_examples.py <example>")
        print("\nAvailable examples:")
        for key, (name, _) in examples.items():
            print(f"  {key}: {name}")
        print("\nExample:")
        print("  python3 poc_rebuild_examples.py 1")
        print("  python3 poc_rebuild_examples.py 5")
